#!/usr/bin/env node
// Folds _data/ai_usage/*.json into AI_USAGE.md.
// Usage: node engine/scripts/usage-ledger.mjs
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { root } from "./lib.mjs";

const DIR = root("_data", "ai_usage");
if (!existsSync(DIR)) { console.log("No usage records yet."); process.exit(0); }

const runs = readdirSync(DIR).filter((f) => f.endsWith(".json"));
const calls = [];
for (const f of runs) {
  try {
    const r = JSON.parse(readFileSync(root("_data", "ai_usage", f), "utf8"));
    for (const c of r.calls ?? []) calls.push({ ...c, workflow: r.workflow ?? "local", run_id: r.run_id });
  } catch { console.error(`skipped unreadable ${f}`); }
}
if (!calls.length) { console.log("No calls on record."); process.exit(0); }

const now = Date.now();
const since = (days) => calls.filter((c) => now - Date.parse(c.at) <= days * 864e5);
const sum = (rows, k) => rows.reduce((a, c) => a + (c[k] ?? 0), 0);
const money = (n) => `$${n.toFixed(2)}`;

const window = (label, rows) =>
  `| ${label} | ${rows.length} | ${sum(rows, "output_tokens").toLocaleString()} | ${money(sum(rows, "cost_usd"))} |`;

const byKey = (rows, key) => {
  const m = new Map();
  for (const c of rows) {
    const k = c[key] ?? "—";
    const e = m.get(k) ?? { calls: 0, output: 0, cost: 0 };
    e.calls++; e.output += c.output_tokens ?? 0; e.cost += c.cost_usd ?? 0;
    m.set(k, e);
  }
  return [...m.entries()].sort((a, b) => b[1].cost - a[1].cost);
};

const billed = calls.filter((c) => c.billed);
const out = [
  "<!-- generated by engine/scripts/usage-ledger.mjs — do not edit by hand -->",
  "# AI Usage & Cost",
  "",
  `_Last rollup: ${new Date().toISOString()}_ · **${calls.length}** model call(s) on record.`,
  "",
  "Every number is **API-equivalent** — what the tokens would bill at list price.",
  "Calls on Claude Code subscription auth (OAuth) cost $0 marginal; only the",
  `metered-key share is real spend. Billed calls so far: **${billed.length}** (${money(sum(billed, "cost_usd"))}).`,
  "",
  "| window | calls | output tokens | cost (API-equiv) |",
  "|---|---|---|---|",
  window("all time", calls),
  window("last 30d", since(30)),
  window("last 7d", since(7)),
  "",
  "## By prompt (all time)",
  "",
  "| prompt | calls | output tokens | cost |",
  "|---|---|---|---|",
  ...byKey(calls, "label").map(([k, v]) => `| \`${k}\` | ${v.calls} | ${v.output.toLocaleString()} | ${money(v.cost)} |`),
  "",
  "## By workflow (all time)",
  "",
  "| workflow | calls | output tokens | cost |",
  "|---|---|---|---|",
  ...byKey(calls, "workflow").map(([k, v]) => `| ${k} | ${v.calls} | ${v.output.toLocaleString()} | ${money(v.cost)} |`),
  "",
  `_Generated from \`_data/ai_usage/\` across ${runs.length} run(s). Don't edit this file by hand._`,
  "",
].join("\n");

writeFileSync(root("AI_USAGE.md"), out, "utf8");
console.log(`Rolled up ${calls.length} calls from ${runs.length} run(s) → AI_USAGE.md`);
